LOCAL_PATH := $(call my-dir)

# Asus Calculator
include $(CLEAR_VARS)
LOCAL_MODULE := AsusCalculator
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/AsusCalculator/AsusCalculator.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := Calculator ExactCalculator
include $(BUILD_PREBUILT)

# Asus Clock 
include $(CLEAR_VARS)
LOCAL_MODULE := AsusClock
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/AsusClock/AsusClock.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := DeskClock
include $(BUILD_PREBUILT)

# Gboard 
include $(CLEAR_VARS)
LOCAL_MODULE := Gboard
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/Gboard/Gboard.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES :=  Keyboard keyboard
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# GcamGo
include $(CLEAR_VARS)
LOCAL_MODULE := CameraGo
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/CameraGo/CameraGo.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := SnapdragonCamera Snap Camera2 Camera
include $(BUILD_PREBUILT)

# Messaging
include $(CLEAR_VARS)
LOCAL_MODULE := Messaging
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := system/priv-app/Messaging//Messaging.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := Messaging messaging Messages messages Message message
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
